'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {ArrowLeft,Download,Eye,X} from 'lucide-react';import {Carousel,CarouselContent,CarouselItem,CarouselNext,CarouselPrevious,type CarouselApi} from '@/components/ui/carousel';import {Footer} from './page';import {galleries,type GalleryDay} from './gallery-data';import {galleryUrl} from '@/lib/gallery-url';
const labels:Record<GalleryDay,string>={septiembre8:'Martes 8 de septiembre',septiembre9:'Miércoles 9 de septiembre'};
export default function Gallery({day}:{day:GalleryDay}){const router=useRouter();const photos=galleries[day];const [authorized,setAuthorized]=useState(false);const [open,setOpen]=useState(false);const [selected,setSelected]=useState(0);const [activePhoto,setActivePhoto]=useState<number|null>(null);const [api,setApi]=useState<CarouselApi>();const label=labels[day];
  useEffect(()=>{if(!localStorage.getItem('nikon-phos-lead'))router.replace('/');else setAuthorized(true)},[router]);useEffect(()=>{if(open&&api)api.scrollTo(selected,true)},[open,api,selected]);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  async function download(url:string,index:number){const resolved=galleryUrl(url);try{const response=await fetch(resolved);const blob=await response.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nikon-phos-${String(index+1).padStart(3,'0')}.jpg`;a.click();URL.revokeObjectURL(a.href)}catch{window.open(resolved,'_blank')}}
  if(!authorized)return <main className="access-loading" aria-label="Verificando registro"/>;
  return <main className="gallery-page"><header className="site-header dark-header"><a href="/"><img src="/nikon-logo_w.svg" alt="Nikon"/></a><img className="gallery-event-logo" src="/logo-phos-footer.svg" alt="Phos"/><a href="/" className="back-link"><ArrowLeft size={17}/> Volver al inicio</a></header><section className="gallery-intro"><p className="eyebrow">Nikon · Phos Uruguay 2026</p><h1>{label}</h1><p>Tocá una fotografía para ver las opciones de previsualización y descarga.</p><span>{photos.length} fotografía{photos.length===1?'':'s'}</span></section>
    {photos.length?<section className="photo-grid">{photos.map((photo,index)=><article className={`photo-card${activePhoto===index?' is-active':''}`} key={`${photo.filename}-${index}`} onClick={()=>setActivePhoto(current=>current===index?null:index)}><img src={galleryUrl(photo.thumb)} alt={`Fotografía ${index+1} de ${label}`} loading={index>7?'lazy':'eager'}/><div className="photo-number">{String(index+1).padStart(3,'0')}</div><div className="photo-actions"><button className="preview-button" onClick={event=>{event.stopPropagation();setSelected(index);setOpen(true)}} aria-label={`Previsualizar fotografía ${index+1}`}><Eye/><span>Previsualizar</span></button><button className="download-trigger" onClick={event=>{event.stopPropagation();download(photo.optimized,index)}} aria-label={`Descargar fotografía ${index+1}`}><Download/><span>Descargar</span></button></div></article>)}</section>:<section className="empty-gallery"><p className="eyebrow">Próximamente</p><h2>Las fotografías se están cargando</h2><p>Volvé a revisar esta jornada en unos minutos.</p></section>}
    <Footer/>{open&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Visor de fotografías"><button className="lightbox-close" onClick={()=>setOpen(false)} aria-label="Cerrar visor"><X/></button><Carousel setApi={setApi} opts={{startIndex:selected}} className="lightbox-carousel"><CarouselContent>{photos.map((photo,index)=><CarouselItem key={`${photo.filename}-slide-${index}`}><div className="slide"><img src={galleryUrl(photo.optimized)} alt={`Fotografía ampliada ${index+1}`}/><div><span>{index+1} / {photos.length}</span><div className="slide-downloads"><button onClick={()=>download(photo.optimized,index)}><Download size={17}/> Descargar</button></div></div></div></CarouselItem>)}</CarouselContent><CarouselPrevious className="lightbox-prev"/><CarouselNext className="lightbox-next"/></Carousel></div>}</main>}
